import React from 'react'
import { BsPeople } from 'react-icons/bs'
import { GrStorage } from 'react-icons/gr'
import { AiOutlineShoppingCart } from 'react-icons/ai'

const AboutStatics = () => {
  return (
    <div className='  bg-backYellow py-16 mt-10'>
      <div className='container text-center mx-auto flex items-center gap-8'>
        <div className='flex flex-col justify-center items-center'>
          <BsPeople className='font-bold text-6xl mb-3' />
          <h3 className='font-krona text-lg'>
            20,000 <br />
            Beauty Experts
          </h3>
          <p className='font-base text-xs mt-1'>
            strive to make their customers more beautiful and thus happier
          </p>
        </div>
        <div className='flex flex-col justify-center items-center'>
          <GrStorage className='font-bold text-6xl mb-3' />
          <h3 className='font-krona text-lg'>
            3.2 <br />
            Billion Euros
          </h3>
          <p className='font-base text-xs mt-1'>
            revenue was generated by Douglas in the 2019/20 financial year
          </p>
        </div>
        <div className='flex flex-col justify-center items-center'>
          <AiOutlineShoppingCart className='font-bold text-6xl mb-3' />
          <h3 className='font-krona text-lg'>
            130,000
            <br />
            Care Products
          </h3>
          <p className='font-base text-xs mt-1'>
            because we care about you in online shops, and in stores
          </p>
        </div>
      </div>
    </div>
  )
}

export default AboutStatics
